Report missing profiles or default as broken module (RhBug:1790967)
Missing default profile will be reported as:
No default profiles for module pki-core:10.6
Error: Problems in request:
broken groups or modules: pki-core

https://bugzilla.redhat.com/show_bug.cgi?id=1790967

Closes: #1579
Approved by: <try>